# docker-compose.yml
version: "3.7"

services:
  QSOLink:
    container_name: qsolink
    image: absenth/qsolink:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "5001:5001"
      - "2345:2345"
    networks:
      - go-qsolink-network
    QSOLink-DB:
      container_name: qsolink-db
      image: postgres
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - qsolink-db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - go-qsolink-network

volumes:
  qsolink-db:

networks:
  go-qsolink-network:
    name: go-qsolink-network
