definitions:
  qso.Qso:
    properties:
      band:
        example: 20
        type: integer
      callsign:
        example: W1AW
        type: string
      city:
        example: New Haven
        type: string
      country:
        example: USA
        type: string
      county:
        example: New Haven
        type: string
      createdAt:
        type: string
      dateon:
        example: "2023-10-28"
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      mode:
        example: cw
        type: string
      name:
        example: John Smith
        type: string
      power:
        example: 100
        type: integer
      qslr:
        example: false
        type: boolean
      qsls:
        example: false
        type: boolean
      remarks:
        example: This is a test contact with W1AW
        type: string
      rstr:
        example: 599
        type: integer
      rsts:
        example: 599
        type: integer
      state:
        example: CT
        type: string
      timeon:
        example: 16:34:58.947Z
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: JSON/REST based Ham Radio Logging Server
  title: QSOLink
paths:
  /api/qso:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/qso.Qso'
            type: array
      summary: Get all QSO records
      tags:
      - QSO
    post:
      consumes:
      - application/json
      parameters:
      - description: QSO data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/qso.Qso'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qso.Qso'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create QSO record
      tags:
      - QSO
  /api/qso/{id}:
    delete:
      parameters:
      - description: QSO ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete QSO record by ID
      tags:
      - QSO
    get:
      parameters:
      - description: QSO ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qso.Qso'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get QSO record by ID
      tags:
      - QSO
    put:
      consumes:
      - application/json
      parameters:
      - description: QSO ID
        in: path
        name: id
        required: true
        type: integer
      - description: QSO data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/qso.Qso'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qso.Qso'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Update QSO record by ID
      tags:
      - QSO
swagger: "2.0"
